"""начальная схема

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 15:56:40.049454
"""

from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phones', sa.JSON(), nullable=False),
    sa.Column('emails', sa.JSON(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('resume_date', sa.Date(), nullable=True),
    sa.Column('parsed', sa.JSON(), nullable=True),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_duplicate_of'), ['duplicate_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_full_name'), ['full_name'], unique=False)

    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_ok', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hard_filters', sa.JSON(), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duplicates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_a', sa.Integer(), nullable=False),
    sa.Column('candidate_b', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['candidate_a'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['candidate_b'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicates_candidate_a'), ['candidate_a'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicates_candidate_b'), ['candidate_b'], unique=False)

    op.create_table('embeddings',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('candidate_id', 'model')
    )
    op.create_table('matches',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('concerns', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ),
    sa.PrimaryKeyConstraint('vacancy_id', 'candidate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('embeddings')
    with op.batch_alter_table('duplicates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicates_candidate_b'))
        batch_op.drop_index(batch_op.f('ix_duplicates_candidate_a'))

    op.drop_table('duplicates')
    op.drop_table('vacancies')
    op.drop_table('settings')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))

    op.drop_table('jobs')
    op.drop_table('import_batches')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_full_name'))
        batch_op.drop_index(batch_op.f('ix_candidates_external_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_duplicate_of'))
        batch_op.drop_index(batch_op.f('ix_candidates_city'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
